Word_List = [
'Turtwig',	
'Grotle',	
'Torterra', 	
'Chimchar',	
'Monferno',	
'Infernape',	
'Piplup',	
'Prinplup',	
'Empoleon',	
'Starly',	
'Staravia',	
'Staraptor',	
'Bidoof',	
'Bibarel',	
'Kricketot',	
'Kricketune',	
'Shinx',	
'Luxio',	
'Luxray',	
'Budew',	
'Roserade',	
'Cranidos',	
'Rampardos',	
'Shieldon',	
'Bastiodon',	
'Burmy Plant Cloak',
'Burmy Sandy Cloak',
'Burmy Trash Cloak',
'Wormadam Plant Cloak',
'Wormadam Sandy Cloak',
'Wormadam Trash Cloak',
'Mothim',	
'Combee',	
'Vespiquen',	
'Pachirisu',	
'Buizel',	
'Floatzel',	
'Cherubi',	
'Cherrim',	
'Shellos',	
'Gastrodon',	
'Ambipom',	
'Drifloon',	
'Drifblim',	
'Buneary',	
'Lopunny',	
'Mismagius',	
'Honchkrow',	
'Glameow',	
'Purugly',	
'Chingling',	
'Stunky',	
'Skuntank',	
'Bronzor',	
'Bronzong',	
'Bonsly',	
'Mime Jr',	
'Happiny',	
'Chatot',	
'Spiritomb',	
'Gible',	
'Gabite',	
'Garchomp',	
'Munchlax',	
'Riolu',	
'Lucario',	
'Hippopotas',	
'Hippowdon',	
'Skorupi',	
'Drapion',	
'Croagunk',	
'Toxicroak',	
'Carnivine',	
'Finneon',	
'Lumineon',	
'Mantyke',	
'Snover',	
'Abomasnow',	
'Weavile',	
'Magnezone',	
'Lickilicky',	
'Rhyperior',	
'Tangrowth',	
'Electivire',	
'Magmortar',	
'Togekiss',	
'Yanmega',	
'Leafeon',	
'Glaceon',	
'Gliscor',	
'Mamoswine',	
'Porygon Z',	
'Gallade',	
'Probopass',	
'Dusknoir',	
'Froslass',	
'Rotom',	
'Rotom Heat Rotom',
'Rotom Wash Rotom',
'Rotom Frost Rotom',
'Rotom Fan Rotom',
'Rotom Mow Rotom',
'Uxie',	
'Mesprit',	
'Azelf',	
'Dialga',	
'Palkia',	
'Heatran',	
'Regigigas',	
'Giratina Altered Forme',
'Giratina Origin Forme',
'Cresselia',	
'Phione',	
'Manaphy',	
'Darkrai',	
'Shaymin Land Forme',
'Shaymin Sky Forme',
'Arceus'	    
]